import {execFileSync} from 'node:child_process';
import {writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {portal} from './sync.mjs';
import {sanitize} from './model.mjs';
const repo='juvalservicesllc-cloud/JUVAl';
export async function githubSnapshot(){
 const state={status:'CONNECTED',checkedAt:new Date().toISOString(),branches:[],pulls:[],issues:[],runs:[],releases:[],alerts:[],warnings:[]};
 const endpoints={branches:['branches?per_page=30','.[] | {name,sha:.commit.sha,protected}'],pulls:['pulls?state=all&per_page=30','.[] | {number,title,state,updated_at,html_url}'],issues:['issues?state=all&per_page=30','.[] | select(.pull_request == null) | {number,title,state,updated_at,html_url}'],runs:['actions/runs?per_page=20','.workflow_runs[] | {name,status,conclusion,head_sha,created_at,html_url}'],releases:['releases?per_page=20','.[] | {name,tag_name,published_at,html_url}'],alerts:['dependabot/alerts?state=open&per_page=30','.[] | {number,state,severity:.security_advisory.severity,package:.dependency.package.name,manifest:.dependency.manifest_path,scope:.dependency.scope,fixed:.security_vulnerability.first_patched_version.identifier,html_url}']};
 for(const [key,[path,query]] of Object.entries(endpoints))try{if(process.env.VERCEL){const response=await fetch(`https://api.github.com/repos/${repo}/${path}`,{headers:{Accept:'application/vnd.github+json'},signal:AbortSignal.timeout(15000)});if(!response.ok)throw new Error('Metadata unavailable');const data=await response.json();const entries=key==='runs'?data.workflow_runs:data;state[key]=JSON.parse(sanitize(JSON.stringify(entries.filter(x=>key!=='issues'||!x.pull_request).map(x=>({number:x.number,name:x.name,title:x.title,state:x.state,status:x.status,conclusion:x.conclusion,head_sha:x.head_sha,sha:x.commit?.sha,protected:x.protected,updated_at:x.updated_at,created_at:x.created_at,published_at:x.published_at,tag_name:x.tag_name,html_url:x.html_url,severity:x.security_advisory?.severity,package:x.dependency?.package?.name,manifest:x.dependency?.manifest_path,scope:x.dependency?.scope,fixed:x.security_vulnerability?.first_patched_version?.identifier})))));continue;}const result=execFileSync('gh',['api',`repos/${repo}/${path}`,'--jq',`[${query}]`],{encoding:'utf8',windowsHide:true,timeout:20000,stdio:['ignore','pipe','pipe']});state[key]=JSON.parse(sanitize(result));}catch{state.warnings.push(`${key}: unavailable (permission, network or missing data); not equivalent to zero.`);state.status='PARTIAL';}
 writeFileSync(resolve(portal,'data/generated/github.json'),JSON.stringify(state,null,2));return state;
}
if(process.argv[1]?.endsWith('github.mjs')){const s=await githubSnapshot();console.log(`GitHub: ${s.status}; ${s.warnings.length} unavailable sources`);}
