import { useState, type FormEvent } from "react"
import { MAX_FILES, SUPPORTED_EXTENSIONS } from "../contract"
import type { FeesIn, Severity, ThresholdsIn } from "../types"

export interface RunFormValues { file: File; files: File[]; thresholds: ThresholdsIn; fees: FeesIn; persist: boolean }
interface Props { disabled: boolean; onSubmit: (values: RunFormValues) => void }
const SEVERITIES: Severity[] = ["NONE", "LOW", "MEDIUM", "HIGH", "CRITICAL"]

export function RunForm({ disabled, onSubmit }: Props) {
  const [files, setFiles] = useState<File[]>([])
  const [dragging, setDragging] = useState(false)
  const [targetProfit, setTargetProfit] = useState(""); const [targetRoi, setTargetRoi] = useState(""); const [minMonthlySales, setMinMonthlySales] = useState(""); const [maxRiskSeverity, setMaxRiskSeverity] = useState<Severity | "">("")
  const [allowRestricted, setAllowRestricted] = useState(false); const [allowApprovalRequired, setAllowApprovalRequired] = useState(false); const [allowUnknownRisk, setAllowUnknownRisk] = useState(false)
  const [referralFee, setReferralFee] = useState(""); const [referralFeeRate, setReferralFeeRate] = useState(""); const [fulfillmentFee, setFulfillmentFee] = useState("0"); const [otherSellingFees, setOtherSellingFees] = useState("0"); const [persist, setPersist] = useState(false); const [formError, setFormError] = useState<string | null>(null)
  function selectFiles(selected: FileList | null) {
    const candidates = Array.from(selected ?? [])
    const supported = (file: File) => SUPPORTED_EXTENSIONS.some((extension) => file.name.toLowerCase().endsWith(extension))
    const rejected = candidates.filter((file) => !supported(file))
    const accepted = candidates.filter(supported)
    const overflow = accepted.slice(MAX_FILES)
    setFiles(accepted.slice(0, MAX_FILES))
    // Overflow and unsupported files are named individually: the operator must
    // be able to see exactly which file did not make it into the queue.
    const messages = [
      rejected.length ? `Only ${SUPPORTED_EXTENSIONS.join(" and ")} files are supported: ${rejected.map((file) => file.name).join(", ")}.` : "",
      overflow.length ? `At most ${MAX_FILES} files per batch, so these were not queued: ${overflow.map((file) => file.name).join(", ")}.` : "",
    ].filter(Boolean)
    setFormError(messages.length ? messages.join(" ") : null)
  }
  function handleSubmit(event: FormEvent) { event.preventDefault(); if (!files.length) return setFormError("Choose at least one catalog file to submit."); if (!targetProfit || !targetRoi || !minMonthlySales || !maxRiskSeverity || !referralFee || !referralFeeRate) return setFormError("Complete every required threshold and fee. JUVAl does not invent commercial defaults."); setFormError(null); onSubmit({ file: files[0], files, thresholds: { target_profit: targetProfit, target_roi: targetRoi, minimum_estimated_monthly_sales: Number(minMonthlySales), maximum_risk_severity: maxRiskSeverity, allow_restricted: allowRestricted, allow_approval_required: allowApprovalRequired, allow_unknown_risk: allowUnknownRisk }, fees: { referral_fee: referralFee, referral_fee_rate: referralFeeRate, fulfillment_fee: fulfillmentFee, other_selling_fees: otherSellingFees }, persist }) }
  return <form onSubmit={handleSubmit} className="run-form" aria-busy={disabled}>
    <fieldset disabled={disabled}><legend>1. Select catalog files</legend><p className="form-help">Queue up to {MAX_FILES} files. Each file becomes its own auditable run; JUVAl imports {SUPPORTED_EXTENSIONS.join(" and ")}.</p><label className={`file-field drop-zone${dragging ? " dragging" : ""}`} onDragEnter={(event) => { event.preventDefault(); if (!disabled) setDragging(true) }} onDragOver={(event) => { event.preventDefault(); if (!disabled) setDragging(true) }} onDragLeave={(event) => { if (!event.currentTarget.contains(event.relatedTarget as Node)) setDragging(false) }} onDrop={(event) => { event.preventDefault(); setDragging(false); if (!disabled) selectFiles(event.dataTransfer.files) }}><span className="drop-zone-hint">Drop catalog files here, or choose them below</span><span className="file-field-label">Catalog files <span aria-hidden="true">*</span></span><input type="file" multiple accept=".xlsx,.csv,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={(event) => selectFiles(event.target.files)} aria-describedby="file-selection" /></label><div id="file-selection" className={`file-selection${files.length ? " selected" : ""}`}>{files.length ? <><ul className="file-queue" aria-label="File queue">{files.map((file, index) => <li key={`${file.name}-${file.size}-${index}`}><span><strong>{file.name}</strong><small>{(file.size / 1024).toFixed(0)} KB · {file.name.toLowerCase().endsWith(".csv") ? "CSV" : "XLSX"} · queued</small></span><button type="button" onClick={() => setFiles((current) => current.filter((_, fileIndex) => fileIndex !== index))} aria-label={`Remove ${file.name}`}>Remove</button></li>)}</ul><p className="queue-count">{files.length} of {MAX_FILES} files queued</p></> : "No file selected."}</div></fieldset>
    <fieldset disabled={disabled}><legend>2. Decision configuration</legend><p className="form-help">These values are submitted to the deterministic pipeline; they are not saved as browser defaults.</p><label>Target profit *<input value={targetProfit} onChange={(event) => setTargetProfit(event.target.value)} inputMode="decimal" placeholder="e.g. 5" /></label><label>Target ROI *<input value={targetRoi} onChange={(event) => setTargetRoi(event.target.value)} inputMode="decimal" placeholder="e.g. 0.3" /></label><label>Minimum estimated monthly sales *<input type="number" min="0" value={minMonthlySales} onChange={(event) => setMinMonthlySales(event.target.value)} placeholder="e.g. 0" /></label><label>Maximum accepted risk severity *<select value={maxRiskSeverity} onChange={(event) => setMaxRiskSeverity(event.target.value as Severity)}><option value="">Select severity</option>{SEVERITIES.map((severity) => <option key={severity} value={severity}>{severity}</option>)}</select></label><label className="checkbox"><input type="checkbox" checked={allowRestricted} onChange={(event) => setAllowRestricted(event.target.checked)} />Allow RESTRICTED</label><label className="checkbox"><input type="checkbox" checked={allowApprovalRequired} onChange={(event) => setAllowApprovalRequired(event.target.checked)} />Allow APPROVAL_REQUIRED</label><label className="checkbox"><input type="checkbox" checked={allowUnknownRisk} onChange={(event) => setAllowUnknownRisk(event.target.checked)} />Allow unknown risk</label></fieldset>
    <fieldset disabled={disabled}><legend>3. Fees and review availability</legend><p className="form-help">Referral fees are required. Persisting stores immutable child run snapshots for review.</p><label>Referral fee *<input aria-label="Referral fee" value={referralFee} onChange={(event) => setReferralFee(event.target.value)} inputMode="decimal" placeholder="e.g. 3" /></label><label>Referral fee rate *<input aria-label="Referral fee rate" value={referralFeeRate} onChange={(event) => setReferralFeeRate(event.target.value)} inputMode="decimal" placeholder="e.g. 0.15" /></label><label>Fulfillment fee<input value={fulfillmentFee} onChange={(event) => setFulfillmentFee(event.target.value)} inputMode="decimal" /></label><label>Other selling fees<input value={otherSellingFees} onChange={(event) => setOtherSellingFees(event.target.value)} inputMode="decimal" /></label><label className="checkbox persist-option"><input type="checkbox" checked={persist} onChange={(event) => setPersist(event.target.checked)} />Persist this run for Runs and later review</label></fieldset>
    {formError && <p role="alert" className="form-error">{formError}</p>}<button type="submit" disabled={disabled}>{disabled ? "Processing catalog…" : files.length > 1 ? `Process ${files.length} files` : "Process catalog"}</button>
  </form>
}
