import { useEffect, useState } from "react"
import { defaultCatalogState, selectCatalog, type CatalogState, type SortField } from "../catalog/select"
import { useDemoApp } from "../app/context"
import { Badge, fmt } from "./shared"
import { productPath } from "../product-route"
import { favoriteKey, sourceIdOf } from "../favorites"
import { ProductThumbnail } from "./ProductThumbnail"
import "./catalog-controls.css"

type FilterKey = "decision" | "brand" | "match" | "hazmat" | "bulky"
const filters: { key: FilterKey; label: string; values: (records: ReturnType<typeof useDemoApp>["records"]) => string[] }[] = [
  { key: "decision", label: "Decision", values: () => ["BUY", "REVIEW", "PASS"] }, { key: "brand", label: "Brand", values: records => [...new Set(records.map(record => record.brand))] }, { key: "match", label: "Amazon", values: () => ["DEMO_FIXTURE", "INFERRED", "NOT_FOUND"] }, { key: "hazmat", label: "Hazmat", values: () => ["PRESENT", "ABSENT", "UNKNOWN"] }, { key: "bulky", label: "Bulky", values: () => ["PRESENT", "ABSENT", "UNKNOWN"] },
]
const stored = () => { try { return { ...defaultCatalogState, ...JSON.parse(sessionStorage.getItem("juval.demo.catalog") || "{}") } as CatalogState } catch { return defaultCatalogState } }
const columns: [string, SortField][] = [["Brand", "brand"], ["Title", "title"], ["Cost", "cost"], ["Suggested", "suggested"], ["Selling", "selling"], ["Profit", "profit"], ["ROI", "roi"], ["Margin", "margin"], ["Hazmat", "hazmat"], ["Bulky", "bulky"], ["Decision", "decision"]]
const percent = (value: number) => `${Number((value * 100).toFixed(2))}%`

export function CatalogPage() {
  const { records, download, active, decisionPolicy, setDecisionPolicy, favorites, toggleFavorite } = useDemoApp()
  const [state, setState] = useState<CatalogState>(stored), [review, setReview] = useState(String(decisionPolicy.reviewRoiThreshold * 100)), [buy, setBuy] = useState(String(decisionPolicy.buyRoiThreshold * 100)), [editingThresholds, setEditingThresholds] = useState(false)
  useEffect(() => sessionStorage.setItem("juval.demo.catalog", JSON.stringify(state)), [state])
  useEffect(() => { setReview(String(decisionPolicy.reviewRoiThreshold * 100)); setBuy(String(decisionPolicy.buyRoiThreshold * 100)) }, [decisionPolicy])
  const shown = selectCatalog(records, state)
  const updateFilter = (key: FilterKey, value: string) => setState(current => ({ ...current, [key]: value, page: 1 }))
  const sort = (field: SortField) => setState(current => { const [currentField, currentDirection] = current.sort.split(":") as [SortField, "asc" | "desc"], next = currentField === field ? (currentDirection === "asc" ? "desc" : "asc") : (field === "roi" || field === "profit" || field === "margin" ? "desc" : "asc"); return { ...current, sort: `${field}:${next}`, page: 1 } })
  const applyPolicy = () => { const policy = { ...decisionPolicy, reviewRoiThreshold: Number(review) / 100, buyRoiThreshold: Number(buy) / 100 }; if (!Number.isFinite(policy.reviewRoiThreshold) || !Number.isFinite(policy.buyRoiThreshold) || policy.reviewRoiThreshold < 0 || policy.reviewRoiThreshold > policy.buyRoiThreshold) { alert("Review threshold must be between 0% and Buy threshold."); return }; setDecisionPolicy(policy); setEditingThresholds(false) }
  const files = active?.files ?? []
  return <>
    <h1>Batch-scoped demo catalog</h1>
    <section className="panel"><h2>Filter results</h2><p>Filters change which records are visible and exported; they never recalculate decisions.</p><div className="filters"><input aria-label="Search catalog" placeholder="Search products" value={state.search} onChange={event => setState(current => ({ ...current, search: event.target.value, page: 1 }))} />{filters.map(filter => <label key={filter.key}>{filter.label}<select aria-label={filter.label} value={state[filter.key]} onChange={event => updateFilter(filter.key, event.target.value)}><option value="">All {filter.label}</option>{filter.values(records).map(value => <option key={value}>{value}</option>)}</select></label>)}<label>Source file<select aria-label="Source file" value={state.sourceFileId} onChange={event => setState(current => ({ ...current, sourceFileId: event.target.value, page: 1 }))}><option value="">All sources</option>{files.map(file => <option key={file.sourceFileId} value={file.sourceFileId}>{file.filename}</option>)}</select></label><label>Minimum ROI filter %<input aria-label="Minimum ROI filter" type="number" value={state.minRoi} onChange={event => setState(current => ({ ...current, minRoi: event.target.value, page: 1 }))} /></label><label>Minimum Profit<input type="number" value={state.minProfit} onChange={event => setState(current => ({ ...current, minProfit: event.target.value, page: 1 }))} /></label><label>Minimum Margin %<input type="number" value={state.minMargin} onChange={event => setState(current => ({ ...current, minMargin: event.target.value, page: 1 }))} /></label><button onClick={() => setState(defaultCatalogState)}>Reset filters</button><button onClick={() => download(shown.all)}>Export {shown.total} results</button></div></section>
    <section className="panel decision-thresholds"><div><h2>Decision thresholds</h2><p>Risk and other blockers still take precedence.</p></div><div className="decision-bands"><strong className="PASS">PASS &lt; {percent(decisionPolicy.reviewRoiThreshold)}</strong><strong className="REVIEW">REVIEW {percent(decisionPolicy.reviewRoiThreshold)}–{percent(Math.max(0, decisionPolicy.buyRoiThreshold - .0001))}</strong><strong className="BUY">BUY ≥ {percent(decisionPolicy.buyRoiThreshold)}</strong></div>{editingThresholds ? <div className="filters"><label>Review from %<input aria-label="Review threshold" type="number" min="0" value={review} onChange={event => setReview(event.target.value)} /></label><label>Buy from %<input aria-label="Buy threshold" type="number" min="0" value={buy} onChange={event => setBuy(event.target.value)} /></label><button onClick={applyPolicy}>Apply decision thresholds</button><button className="secondary" onClick={() => setEditingThresholds(false)}>Cancel</button></div> : <button className="secondary" onClick={() => setEditingThresholds(true)}>Edit thresholds</button>}</section>
    <div className="table"><table><thead><tr><th>Image</th><th>Source</th>{columns.map(([label, field]) => { const activeSort = state.sort.startsWith(`${field}:`), direction = activeSort ? state.sort.split(":")[1] : "none"; return <th key={field} aria-sort={activeSort ? (direction === "asc" ? "ascending" : "descending") : "none"}><button onClick={() => sort(field)}>{label} {activeSort ? (direction === "asc" ? "↑" : "↓") : "↕"}</button></th> })}<th>Favorite</th></tr></thead><tbody>{shown.items.map(record => { const sourceFileId = sourceIdOf(record), key = active ? favoriteKey(active.runId, sourceFileId, record.recordRef) : "", favorite = favorites.includes(key); return <tr key={key || record.recordRef}><td><ProductThumbnail src={record.image} alt={`${record.brand} ${record.title}`} /></td><td><small title={record.sourceFilename}>{record.sourceFilename ?? "—"}</small></td><td>{record.brand}</td><td>{active ? <a href={productPath(active.runId, sourceFileId, record.recordRef)}>{record.title}</a> : record.title}</td><td>{fmt(record.cost, "$")}</td><td>{fmt(record.suggested, "$")}</td><td>{fmt(record.selling, "$")}</td><td>{fmt(record.profit, "$")}</td><td>{record.roi === null ? "—" : `${(record.roi * 100).toFixed(1)}%`}</td><td>{record.margin === null ? "—" : `${(record.margin * 100).toFixed(1)}%`}</td><td>{record.hazmat}</td><td>{record.bulky}</td><td><Badge>{record.decision}</Badge></td><td>{active && <button className="favorite-button" aria-label={`${favorite ? "Remove" : "Add"} ${record.title} ${favorite ? "from" : "to"} favorites`} aria-pressed={favorite} onClick={event => { event.stopPropagation(); toggleFavorite(active.runId, sourceFileId, record.recordRef) }}>{favorite ? "★" : "☆"}</button>}</td></tr> })}</tbody></table></div>
    <p><button disabled={shown.page === 1} onClick={() => setState(current => ({ ...current, page: shown.page - 1 }))}>Previous</button> Page {shown.page} of {shown.pages} <button disabled={shown.page === shown.pages} onClick={() => setState(current => ({ ...current, page: shown.page + 1 }))}>Next</button></p>
  </>
}
