import {t} from './i18n';
import {useState} from 'react';
import type {Criterion} from './model';
export interface Debt {id:string;title:string;category:string;severity:string;effort:string;impact:string;status:string;source:string;evidence:string;nextAction:string}
export function DebtRegister({items,inspect}:{items:Debt[];inspect:(source:string)=>void}){
 const [query,setQuery]=useState('');
 return <><div className="notice">{t("Identifiers below are assigned by this portal. PERF-ID-01 / PERF-ID-02 / HARD-ID-01 were not found as identifiers in the indexed repository; matching performance behaviors are evidenced separately. No severity or effort estimate is invented.")}</div><div className="filters"><input aria-label={t("Search technical debt")} placeholder={t("Search debt, impact or source…")} value={query} onChange={e=>setQuery(e.target.value)}/></div>{t(items.filter(d=>JSON.stringify(d).toLowerCase().includes(query.toLowerCase())).map(d=><section className="panel" key={d.id}><div className="panel-heading"><h2>{t(d.title)}</h2><code>{d.id}</code></div><dl><dt>{t("Category / status")}</dt><dd>{t(d.category)}{t(" · ")}{t(d.status)}</dd><dt>{t("Severity / effort")}</dt><dd>{t(d.severity)}{t(" · ")}{t(d.effort)}</dd><dt>{t("Impact")}</dt><dd>{t(d.impact)}</dd><dt>{t("Evidence")}</dt><dd><code>{d.evidence}</code></dd><dt>{t("Next action")}</dt><dd>{t(d.nextAction)}</dd><dt>{t("Phase / owner")}</dt><dd>{t("Identity & Access · Unassigned")}</dd><dt>{t("Dependencies")}</dt><dd>{t("Representative load measurements")}</dd></dl><button onClick={()=>inspect(d.source)}>{t("Inspect source ↗")}</button></section>))}{t(!items.length&&<section className="panel empty"><h2>{t("No matching debt evidence")}</h2><p>{t("No technical-debt entries were derived from the allowlisted sources.")}</p></section>)}</>;
}
export function ControlMatrix({items,inspect}:{items:Criterion[];inspect:(c:Criterion)=>void}){return <div className="control-matrix">{t(items.map(c=><details key={c.id} className="control-detail"><summary><b>{t(c.title)}</b><span>{t(c.status.replaceAll('_',' '))}</span></summary><div className="control-columns"><div><h3>{t("Implementation")}</h3><p>{t(c.status.replaceAll('_',' '))}</p><small>{t(c.description)}</small></div><div><h3>{t("Verification")}</h3><p>{t(c.verificationLevel.replaceAll('_',' '))}</p><small>{t("Production: not independently verified")}</small></div><div><h3>{t("Gap / required action")}</h3><p>{t(c.notes||'Provide dated effective-control evidence and close the documented residual gap.')}</p><small>{t("Blocks reapplication: ")}{t(c.status==='COMPLETE'?'No criterion gap':'Yes')}{t(" · Owner: unassigned")}</small></div></div><button onClick={()=>inspect(c)}>{t("Inspect evidence and dependencies ↗")}</button></details>))}</div>;}
