import {progress as calculate} from '../scripts/model.mjs';
export type Status='COMPLETE'|'IN_PROGRESS'|'PARTIAL'|'BLOCKED'|'NOT_STARTED'|'DEFERRED';
export interface Criterion {evidenceSource?:string;runtimeVerification?:string;sourceUpdatedAt?:string|null;id:string;title:string;description:string;status:Status;weight:number;phase:number;workstream:string;source:string;sourceReference:string;evidence:string;lastUpdated:string;confidence:string;verificationLevel:string;blockedBy:string[];dependsOn:string[];notes:string;commit:string;parser:string;relatedAdrs:string[]}
export interface Adr {id:string;title:string;status:string;date:string|null;source:string;context:string;decision:string;consequences:string;supersededBy:string|null}
export interface RepoFile {path:string;title:string;content:string;kind:string}
export interface Commit {hash:string;date:string;author:string;title:string}
export interface State {evidenceSources?:Record<string,unknown>;recordedObservations?:{source:string;sourceReference:string;evidence:string;scope:string;runtimeVerification:string}[];debt?:import('./assurance').Debt[];schemaVersion:number;model:string;phases:string[];criteria:Criterion[];adrs:Adr[];files:RepoFile[];commits:Commit[];tests:{discoveredFiles:string[];run:null|{passed:number;failed:number;skipped:number;total:number;at:string;head:string};coverage:string;flaky:string};git:{branch:string;head:string;divergence:number[]|null;dirty:boolean;untrackedPresent:boolean;repository:string;tags:string[]};github:{status:string;checkedAt:string|null;branches:unknown[];pulls:unknown[];issues:unknown[];runs:unknown[];releases:unknown[];alerts:unknown[];error?:string};sync:{mode:string;lastAttempted:string;lastSuccessful:string;status:string;filesScanned:number;commitsProcessed:number;warnings:string[];errors:string[];history:{at:string;status:string;head:string}[]}}
export function progress(items:Criterion[],verification=false){return calculate(items,verification?"verification":"implementation");}
export function priority(c:Criterion,all:Criterion[]){return (c.status==='BLOCKED'?3:c.status==='COMPLETE'?1:2)*(c.weight>=3?3:2)+all.filter(x=>x.dependsOn.includes(c.id)).length*2;}
