import {t} from './i18n';
import {useState} from 'react';
import type {Criterion,State} from './model';
export function RiskRegister({items,inspect}:{items:Criterion[];inspect:(c:Criterion)=>void}){
 const [view,setView]=useState('Table');
 const likelihood=(c:Criterion)=>c.status==='BLOCKED'?3:c.status==='COMPLETE'?1:2;
 const impact=(c:Criterion)=>c.weight>=3?3:2;
 return <><div className="tabs">{t(['Table','Cards','Matrix'].map(v=><button key={v} className={view===v?'selected':''} onClick={()=>setView(v)}>{t(v)}</button>))}</div><div className="notice">{t("Risk IDs reference acceptance criteria. Likelihood and impact are transparent triage proxies (status × weight), not observed probabilities. Completed criteria are shown separately from residual gaps.")}</div>{t(view==='Matrix'?<section className="panel"><h2>{t("Likelihood proxy × impact proxy")}</h2><div className="risk-matrix">{t([3,2,1].flatMap(l=>[1,2,3].map(i=><div className={`risk-cell risk-${l*i>=6?'high':'low'}`} key={`${l}-${i}`}><b>{t(l)}{t(" × ")}{t(i)}</b>{t(items.filter(c=>likelihood(c)===l&&impact(c)===i).map(c=><button key={c.id} onClick={()=>inspect(c)}>{t(c.title)}</button>))}</div>)))}</div></section>:<div className={view==='Cards'?'tile-grid':''}>{t([false,true].map(resolved=><section className="panel" key={String(resolved)}><h2>{t(resolved?'Completed criteria · residual runtime risk may remain':'Open risks & residual gaps')}</h2>{t(items.filter(c=>(c.status==='COMPLETE')===resolved).map(c=><details key={c.id} className="control-detail"><summary><b>{t(c.title)}</b><code>{c.id}</code></summary><dl><dt>{t("Status / category")}</dt><dd>{t(c.status)}{t(" · ")}{t(c.workstream)}</dd><dt>{t("Severity proxy")}</dt><dd>{t(likelihood(c)*impact(c)>=6?'High':'Moderate / low')}{t(" · ")}{t(likelihood(c))}{t(" × ")}{t(impact(c))}</dd><dt>{t("Owner")}</dt><dd>{t("Unassigned")}</dd><dt>{t("Mitigation")}</dt><dd>{t(c.notes||'Close the criterion with dated evidence; review remaining verification gaps.')}</dd><dt>{t("Blocking?")}</dt><dd>{t(c.blockedBy.length?c.blockedBy.join(', '):c.status==='BLOCKED'?'External approval or evidence':'No unresolved dependencies')}</dd><dt>{t("Related milestone")}</dt><dd>{t("Phase ")}{t(c.phase)}{t(" · ")}{t(c.title)}</dd><dt>{t("Related ADRs")}</dt><dd>{t(c.relatedAdrs.join(', ')||'None identified')}</dd><dt>{t("Evidence")}</dt><dd>{t(c.sourceReference)}</dd></dl><button onClick={()=>inspect(c)}>{t("Full evidence ↗")}</button></details>))}</section>))}</div>)}</>;
}
export function GithubPanel({github}:{github:State['github']}){
 const [view,setView]=useState('pulls');
 const unavailable=(github as State['github']&{warnings?:string[]}).warnings??[];
 const entries=github[view as 'pulls'] as Record<string,unknown>[];
 return <section className="panel"><div className="panel-heading"><h2>{t("GitHub · repository activity")}</h2><span className="badge">{t(github.status)}</span></div><p className="muted">{t("Checked ")}{t(github.checkedAt??'Never')}{t(" · bounded metadata snapshot · alerts require triage, not an exploitability conclusion.")}</p><div className="tabs wrap">{t(['pulls','issues','runs','branches','releases','alerts'].map(v=><button key={v} className={view===v?'selected':''} onClick={()=>setView(v)}>{t(v==='pulls'?'Pull requests':v)}{t(" (")}{t(github[v as 'pulls'].length)}{t(")")}</button>))}</div>{t(unavailable.map(w=><div className="notice" key={w}>{t(w)}</div>))}{t(entries.length?entries.map((entry,i)=><div className="row" key={i}><span><b>{t(String(entry.title??entry.name??entry.package??`#${entry.number}`))}</b><small>{t(String(entry.manifest??entry.updated_at??entry.created_at??entry.published_at??entry.sha??''))}{t(entry.fixed?` · Fixed version ${entry.fixed}`:'')}{t(entry.scope?` · ${entry.scope}`:'')}</small></span><span className="badge">{t(String(entry.severity??entry.conclusion??entry.state??entry.status??'Recorded'))}</span>{t(typeof entry.html_url==='string'&&entry.html_url.startsWith('https://github.com/')&&<a href={entry.html_url} target="_blank" rel="noreferrer">{t("Open ↗")}</a>)}</div>):<div className="empty">{t(unavailable.some(w=>w.startsWith(view))?'This source is unavailable.':'No entries returned by this bounded query.')}</div>)}</section>;
}
