"""Application-layer encryption for OAuth tokens at rest (ADR-036).

Why this exists even though the database encrypts at rest
---------------------------------------------------------
Supabase/PostgreSQL encryption at rest protects the *disk*. It does not
protect against anything that can read the table: a leaked database URL, a
misconfigured role, a support query, a backup file, a `SELECT *` in someone's
console. An access token in a readable column is a bearer credential in a
readable column. Amazon's Data Protection Policy Sec. 1.4.2 requires
programmatic credentials to be stored securely and not exposed; "the provider
encrypts the volume" does not discharge that. So the ciphertext is produced and
consumed by JUVAl, and the key never enters the database.

No custom cryptography
----------------------
AES-256-GCM from `cryptography` (already a transitive dependency via
`pyjwt[crypto]`; no new package). GCM is an AEAD: one primitive gives
confidentiality *and* integrity, so a tampered ciphertext fails to decrypt
rather than silently yielding garbage. Nothing here composes primitives by
hand.

Format (versioned on purpose)
-----------------------------
    v1.<key_id>.<base64url(nonce)>.<base64url(ciphertext||tag)>

* `v1` -- the scheme. A future `v2` (different cipher, different KDF) can be
  introduced and read alongside `v1`, so rotation never requires a flag day.
* `key_id` -- which key encrypted this. Rotation is additive: add a new key as
  primary, keep the old one available for decryption, re-encrypt lazily on
  next write, then drop the old key when no `v1.<old>` rows remain.
* `nonce` -- 96-bit, freshly random per encryption. **Never reused**: GCM
  catastrophically loses confidentiality *and* authenticity on nonce reuse
  under the same key, which is why it is generated per call from
  `os.urandom` and never derived from anything.

Associated data
---------------
Every encryption binds the ciphertext to the row and field it belongs to
(`session id digest` + field name). Moving a refresh-token ciphertext into the
access-token column, or into another user's row, fails authentication instead
of decrypting. Confidentiality alone would not catch that.

Key custody
-----------
Keys come from the environment, never from the database, never from a file in
this repository, and never from a `VITE_*` variable (those are compiled into
the browser bundle). Nothing in this module logs, prints, or returns a key, a
plaintext token, or a ciphertext fragment.
"""

from __future__ import annotations

import base64
import os
from dataclasses import dataclass
from typing import Dict, Mapping, Optional, Tuple

from cryptography.exceptions import InvalidTag
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

SCHEME = "v1"
_NONCE_BYTES = 12          # 96-bit, the size GCM is defined and analysed for
_KEY_BYTES = 32            # AES-256
_SEPARATOR = "."

#: Environment variable holding the keyring. Format:
#:     <key_id>:<base64 32-byte key>[,<key_id>:<base64 32-byte key>...]
#: The FIRST entry is the primary and is used for every new encryption; all
#: entries can decrypt. Deployment-specific secret -- never committed, never
#: defaulted, never generated by this code.
KEYRING_ENV = "JUVAL_SESSION_ENCRYPTION_KEYS"


class TokenCryptoError(RuntimeError):
    """Base class. Never carries a key, a token, or a ciphertext."""


class TokenCryptoUnavailable(TokenCryptoError):
    """No usable keyring is configured."""


class TokenDecryptionError(TokenCryptoError):
    """Ciphertext could not be authenticated and decrypted.

    Deliberately one error for every cause -- wrong key, unknown key id,
    corrupt ciphertext, wrong associated data, unsupported scheme. Reporting
    which one it was would turn this into a padding-oracle-shaped signal, and
    every cause has the same correct response: treat the session as invalid.
    """


@dataclass(frozen=True)
class _Key:
    key_id: str
    material: bytes


class TokenCipher:
    """Encrypts and decrypts short secrets (OAuth tokens) for storage.

    Construct via `from_environment()` in production. The constructor takes
    explicit keys so tests can exercise rotation and wrong-key behaviour with
    locally generated material and no environment at all.
    """

    def __init__(self, primary: _Key, others: Tuple[_Key, ...] = ()) -> None:
        self._primary = primary
        self._by_id: Dict[str, _Key] = {primary.key_id: primary}
        for key in others:
            self._by_id.setdefault(key.key_id, key)

    # -- construction ---------------------------------------------------

    @classmethod
    def from_environment(cls, env: Optional[Mapping[str, str]] = None) -> "TokenCipher":
        raw = (env if env is not None else os.environ).get(KEYRING_ENV, "").strip()
        if not raw:
            raise TokenCryptoUnavailable(
                f"{KEYRING_ENV} is not set; durable sessions cannot store tokens "
                "without an encryption key (ADR-036)"
            )
        keys = [cls._parse_entry(entry) for entry in raw.split(",") if entry.strip()]
        if not keys:
            raise TokenCryptoUnavailable(f"{KEYRING_ENV} contains no usable key entry")
        return cls(primary=keys[0], others=tuple(keys[1:]))

    @staticmethod
    def _parse_entry(entry: str) -> _Key:
        key_id, sep, encoded = entry.strip().partition(":")
        if not sep or not key_id or _SEPARATOR in key_id:
            raise TokenCryptoUnavailable(
                f"{KEYRING_ENV} entries must be '<key_id>:<base64 key>' and the key id "
                f"must not contain '{_SEPARATOR}'"
            )
        try:
            material = base64.b64decode(encoded, validate=True)
        except Exception as exc:  # noqa: BLE001 - the reason is never echoed
            raise TokenCryptoUnavailable(f"{KEYRING_ENV}: key '{key_id}' is not valid base64") from exc
        if len(material) != _KEY_BYTES:
            raise TokenCryptoUnavailable(
                f"{KEYRING_ENV}: key '{key_id}' must be exactly {_KEY_BYTES} bytes "
                f"({_KEY_BYTES * 8}-bit) before base64 encoding"
            )
        return _Key(key_id=key_id, material=material)

    # -- use -------------------------------------------------------------

    @property
    def primary_key_id(self) -> str:
        """Which key new ciphertext is produced with. Safe to log: it is an
        identifier, not key material."""
        return self._primary.key_id

    def encrypt(self, plaintext: str, *, context: str) -> str:
        """Encrypt `plaintext`, binding it to `context` (row + field)."""
        nonce = os.urandom(_NONCE_BYTES)
        sealed = AESGCM(self._primary.material).encrypt(
            nonce, plaintext.encode("utf-8"), context.encode("utf-8")
        )
        return _SEPARATOR.join(
            (SCHEME, self._primary.key_id, _b64(nonce), _b64(sealed))
        )

    def decrypt(self, envelope: str, *, context: str) -> str:
        """Decrypt and authenticate. Raises `TokenDecryptionError` on any fault."""
        try:
            scheme, key_id, nonce_b64, sealed_b64 = envelope.split(_SEPARATOR, 3)
        except ValueError as exc:
            raise TokenDecryptionError("malformed ciphertext envelope") from exc
        if scheme != SCHEME:
            raise TokenDecryptionError("unsupported ciphertext scheme")
        key = self._by_id.get(key_id)
        if key is None:
            # The key was rotated out, or this row came from another
            # deployment. Same response either way: the session is unusable.
            raise TokenDecryptionError("no key available for this ciphertext")
        try:
            plaintext = AESGCM(key.material).decrypt(
                _unb64(nonce_b64), _unb64(sealed_b64), context.encode("utf-8")
            )
        except (InvalidTag, ValueError, TypeError) as exc:
            raise TokenDecryptionError("ciphertext failed authentication") from exc
        return plaintext.decode("utf-8")

    def needs_reencryption(self, envelope: str) -> bool:
        """True when `envelope` was produced by an older scheme or key.

        Lets the adapter re-encrypt opportunistically on a write it was going
        to make anyway, so rotation completes without a migration job.
        """
        parts = envelope.split(_SEPARATOR, 3)
        if len(parts) != 4:
            return True
        return parts[0] != SCHEME or parts[1] != self._primary.key_id


def context_for(session_digest: str, field: str) -> str:
    """Associated data binding a ciphertext to one row and one column."""
    return f"juval.session.{SCHEME}|{session_digest}|{field}"


def _b64(raw: bytes) -> str:
    return base64.urlsafe_b64encode(raw).decode("ascii").rstrip("=")


def _unb64(value: str) -> bytes:
    return base64.urlsafe_b64decode(value + "=" * (-len(value) % 4))
