import type { CsvParseResult } from "../csv/parseCsv"

export type Provenance = "VERIFIED_SOURCE" | "DEMO_FIXTURE" | "INFERRED" | "NOT_FOUND" | "INVALID"
export type Decision = "BUY" | "REVIEW" | "PASS"
export type DemoRecord = { recordRef:string; url:string; image:string; brand:string; title:string; cost:number|null; suggested:number|null; raw:Record<string,string>; asin:string|null; match:Provenance; selling:number|null; fees:number|null; shipping:number|null; weight:number|null; hazmat:string; bulky:string; profit:number|null; roi:number|null; margin:number|null; decision:Decision; reasons:string[]; issues:string[]; trace:string[];sourceFileId?:string;sourceFilename?:string;sourceFileType?:"CSV"|"XLSX";sourceRowNumber?:number }
export type Analytics = { total:number; decisions:Record<Decision,number>; match:Record<string,number>; hazards:Record<string,number>; bulky:Record<string,number>; brands:[string,number][]; issues:number; issueTypes:[string,number][]; profit:number; avgRoi:number|null; avgMargin:number|null; fixtureMatches:number; inferredMatches:number; asinNotFound:number; hazmatPresent:number; bulkyPresent:number; priceAnalysis:{valid:number; averageDiscount:number|null; atOrAboveSuggested:number; largestDiscounts:{recordRef:string;title:string;amount:number;percent:number|null}[]}; topOpportunities:{recordRef:string;title:string;profit:number}[] }
export const ENGINE_VERSION="demo-engine-2"
export const DEMO_DECISION_MODEL_VERSION="1.0"
export type DemoDecisionPolicy={modelVersion:string;reviewRoiThreshold:number;buyRoiThreshold:number}
export const DEMO_DECISION_CONFIG={passRoiThreshold:.15,buyRoiThreshold:.35} as const
export const defaultDecisionPolicy:DemoDecisionPolicy={modelVersion:DEMO_DECISION_MODEL_VERSION,reviewRoiThreshold:DEMO_DECISION_CONFIG.passRoiThreshold,buyRoiThreshold:DEMO_DECISION_CONFIG.buyRoiThreshold}
export const validDecisionPolicy=(policy:DemoDecisionPolicy)=>Number.isFinite(policy.reviewRoiThreshold)&&Number.isFinite(policy.buyRoiThreshold)&&policy.reviewRoiThreshold>=0&&policy.reviewRoiThreshold<=policy.buyRoiThreshold
export function decideDemo(input:{profit:number|null;roi:number|null;match:Provenance;hazmat:string;bulky:string},policy:DemoDecisionPolicy=defaultDecisionPolicy):{decision:Decision;reasons:string[]}{if(!validDecisionPolicy(policy))throw new Error("Decision ROI policy must be ordered from 0 upward.");const{profit,roi,match,hazmat,bulky}=input;if(profit===null||match==="NOT_FOUND"||hazmat==="PRESENT"||roi===null||roi<policy.reviewRoiThreshold)return{decision:"PASS",reasons:[profit===null?"Missing supplier price":match==="NOT_FOUND"?"Amazon demo match not found":hazmat==="PRESENT"?"Hazmat status blocks demo decision":"ROI below demo target"]};if(match==="INFERRED"||hazmat==="UNKNOWN"||bulky!=="ABSENT"||roi<policy.buyRoiThreshold)return{decision:"REVIEW",reasons:[match==="INFERRED"?"Amazon demo match is inferred":"Risk requires verification","Review demo enrichment before sourcing"]};return{decision:"BUY",reasons:["ROI above demo target","No blocking demo risk"]}}
export const applyDecisionPolicy=(records:DemoRecord[],policy:DemoDecisionPolicy)=>records.map(record=>({...record,...decideDemo(record,policy)}))
const hash=(s:string)=>[...s].reduce((n,c)=>(n*31+c.charCodeAt(0))>>>0,7)
const round=(n:number)=>Number(n.toFixed(2))
export const money=(value:string)=>{const normalized=value.replace(/[^0-9.-]/g,"");if(!normalized||normalized==="-"||normalized===".")return null;const parsed=Number(normalized);return Number.isFinite(parsed)?parsed:null}
export function normalize(parsed:CsvParseResult):DemoRecord[]{return parsed.rows.map((raw,index)=>{
  const brand=(raw["product-brand-name"]||"Unknown").trim(), title=(raw.link||"Untitled supplier item").trim(), cost=money(raw["item-price"]||""), suggested=money(raw["item-price (2)"]||"")
  // Row index disambiguates duplicate supplier rows while stable source fields keep this run-scoped reference reproducible.
  const recordRef=`wm-${String(index+1).padStart(4,"0")}-${hash(`${brand}|${title}|${raw["position-relative href"]||""}`).toString(36)}`, n=hash(recordRef)
  const match:Provenance=n%7===0?"NOT_FOUND":n%4===0?"INFERRED":"DEMO_FIXTURE", asin=match==="NOT_FOUND"?null:`D${n.toString(36).toUpperCase().padStart(9,"0").slice(0,9)}`
  const selling=cost===null?null:round((suggested??cost*1.65)*(1.02+(n%20)/100)), fees=selling===null?null:round(selling*.15+3.2), shipping=cost===null?null:round(1+(n%5)*.55)
  const profit=cost===null||selling===null||fees===null||shipping===null?null:round(selling-cost-fees-shipping), roi=profit===null||cost===null||cost===0?null:round(profit/cost), margin=profit===null||selling===null||selling===0?null:round(profit/selling)
  const hazmat=n%11===0?"PRESENT":n%6===0?"UNKNOWN":"ABSENT", bulky=n%13===0?"PRESENT":n%8===0?"UNKNOWN":"ABSENT", weight=n%5?round(.5+(n%40)/10):null
  const {decision,reasons}=decideDemo({profit,roi,match,hazmat,bulky})
  return {recordRef,url:raw["position-relative href"]||"",image:raw["img-fluid src"]||"",brand,title,cost,suggested,raw,asin,match,selling,fees,shipping,weight,hazmat,bulky,profit,roi,margin,decision,reasons,issues:[...(cost===null?["Invalid or missing Supplier / Your Price"]:[]),...(match==="NOT_FOUND"?["Amazon demo match not found"]:[])],trace:["SOURCE_IMPORTED","NORMALIZED","DEMO_AMAZON_ENRICHED","DEMO_RISK_ENRICHED","PROFITABILITY_CALCULATED","DECISION_CALCULATED"]}
})}
export function analytics(records:DemoRecord[]):Analytics { const count=(values:string[])=>Object.fromEntries(values.map(value=>[value,records.filter(r=>values.includes(r.decision)?r.decision===value:r.match===value).length])); const numeric=(key:"roi"|"margin")=>{const xs=records.map(r=>r[key]).filter((value):value is number=>value!==null);return xs.length?round(xs.reduce((a,b)=>a+b,0)/xs.length):null};const prices=records.filter((r):r is DemoRecord&{cost:number;suggested:number}=>r.cost!==null&&r.suggested!==null).map(r=>({recordRef:r.recordRef,title:r.title,amount:round(r.suggested-r.cost),percent:r.suggested===0?null:round((r.suggested-r.cost)/r.suggested)}));const issueTypes=Object.entries(records.flatMap(r=>r.issues).reduce<Record<string,number>>((a,issue)=>(a[issue]=(a[issue]||0)+1,a),{})).sort((a,b)=>b[1]-a[1]);return {total:records.length,decisions:count(["BUY","REVIEW","PASS"]) as Record<Decision,number>,match:count(["DEMO_FIXTURE","INFERRED","NOT_FOUND"]),hazards:Object.fromEntries(["PRESENT","ABSENT","UNKNOWN"].map(x=>[x,records.filter(r=>r.hazmat===x).length])),bulky:Object.fromEntries(["PRESENT","ABSENT","UNKNOWN"].map(x=>[x,records.filter(r=>r.bulky===x).length])),brands:Object.entries(records.reduce<Record<string,number>>((a,r)=>(a[r.brand]=(a[r.brand]||0)+1,a),{})).sort((a,b)=>b[1]-a[1]).slice(0,8),issues:records.reduce((n,r)=>n+r.issues.length,0),issueTypes,profit:round(records.reduce((n,r)=>n+(r.profit??0),0)),avgRoi:numeric("roi"),avgMargin:numeric("margin"),fixtureMatches:records.filter(r=>r.match==="DEMO_FIXTURE").length,inferredMatches:records.filter(r=>r.match==="INFERRED").length,asinNotFound:records.filter(r=>r.match==="NOT_FOUND").length,hazmatPresent:records.filter(r=>r.hazmat==="PRESENT").length,bulkyPresent:records.filter(r=>r.bulky==="PRESENT").length,priceAnalysis:{valid:prices.length,averageDiscount:prices.length?round(prices.reduce((sum,p)=>sum+p.amount,0)/prices.length):null,atOrAboveSuggested:prices.filter(p=>p.amount<=0).length,largestDiscounts:[...prices].sort((a,b)=>b.amount-a.amount||a.recordRef.localeCompare(b.recordRef)).slice(0,5)},topOpportunities:records.filter((r):r is DemoRecord&{profit:number}=>r.profit!==null).map(r=>({recordRef:r.recordRef,title:r.title,profit:r.profit})).sort((a,b)=>b.profit-a.profit||a.recordRef.localeCompare(b.recordRef)).slice(0,5)}}
export function exportCsv(records:DemoRecord[],batchId?:string){const headers=["batch_id","source_filename","source_file_type","source_row_number","record_ref","supplier_url","brand","supplier_title","supplier_cost","suggested_price","asin","amazon_provenance","selling_price_demo","fees_demo","profit_demo","roi_demo","margin_demo","hazmat_demo","bulky_demo","decision_demo","decision_reasons","issues"];const quote=(value:unknown)=>`"${String(value??"").replaceAll('"','""')}"`;return [headers.join(","),...records.map(r=>[batchId??"",r.sourceFilename??"",r.sourceFileType??"",r.sourceRowNumber??"",r.recordRef,r.url,r.brand,r.title,r.cost,r.suggested,r.asin,r.match,r.selling,r.fees,r.profit,r.roi,r.margin,r.hazmat,r.bulky,r.decision,r.reasons.join("; "),r.issues.join("; ")].map(quote).join(","))].join("\r\n")}
