"""Idempotently configure the JUVAl tenant, application and roles in FusionAuth.

Turns `deploy/fusionauth/tenant-password-policy.template.json` and the role
table in `interfaces/api/auth.py` into real FusionAuth objects, so the
configuration is reproducible from Git rather than existing only as clicks in
the admin UI (CLAUDE.md §"AUTOMATION / REPRODUCIBILITY").

What it does, each step checking its end state first so a re-run is a no-op:

  1. verify the instance answers and the API key works;
  2. find-or-create a tenant named "JUVAl" (never the Default tenant, which
     belongs to FusionAuth administration -- ADR-031 §"Alcance exacto");
  3. apply the password/lockout/MFA policy from the template, plus the two
     controls that sit outside `passwordValidationRules` (minimum/maximum
     password age);
  4. find-or-create an application named "JUVAl" under that tenant, with the
     least-privilege OAuth grant set (`authorization_code` + `refresh_token`,
     PKCE required, no implicit, no client-credentials);
  5. ensure exactly the roles `interfaces/api/auth.py` maps: viewer, operator,
     admin.

Secret hygiene, matching `tools/verify_oidc.py`:

  * the API key is read from `JUVAL_IDP_API_KEY` in the environment and is
    never accepted as an argument, so it cannot land in shell history;
  * no key, token or secret is ever printed. The application *id* is printed
    -- it is the OAuth client id / `aud` value, which is not a secret and is
    needed to configure the backend.

UUIDs are generated by FusionAuth (POST without an id), never invented here.

Usage:
    JUVAL_IDP_API_KEY=... python tools/configure_fusionauth.py
    JUVAL_IDP_API_KEY=... python tools/configure_fusionauth.py --issuer https://idp.example.com
    JUVAL_IDP_API_KEY=... python tools/configure_fusionauth.py --dry-run

Exit code is non-zero on any failure.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any, Optional

REPO_ROOT = Path(__file__).resolve().parent.parent
TEMPLATE = REPO_ROOT / "deploy" / "fusionauth" / "tenant-password-policy.template.json"

TENANT_NAME = "JUVAl"
APPLICATION_NAME = "JUVAl"

# Must match interfaces/api/auth.py::ROLE_PERMISSIONS exactly. The backend is
# the authority on role names; this list is checked against it by a test.
REQUIRED_ROLES = ("viewer", "operator", "admin")

# Least privilege (CLAUDE.md §4): the only grants a future PWA login needs.
# Implicit flow and client-credentials are deliberately absent.
LEAST_PRIVILEGE_GRANTS = ["authorization_code", "refresh_token"]

# Amazon controls 8 and 9 (SP_API_REGISTRATION_REMEDIATION.md). They live on
# the tenant object, outside passwordValidationRules, which is why the template
# records them in `_controls_not_expressible_here` rather than inline.
MINIMUM_PASSWORD_AGE_SECONDS = 86_400        # control 8: >= 1 day
MAXIMUM_PASSWORD_AGE_DAYS = 365              # control 9: <= 365 days

TIMEOUT = 15


class ConfigError(RuntimeError):
    pass


class Client:
    """Minimal FusionAuth API client. Prints no secret."""

    def __init__(self, base: str, api_key: str, dry_run: bool) -> None:
        self._base = base.rstrip("/")
        self._api_key = api_key
        self._dry_run = dry_run

    def _request(self, method: str, path: str, body: Optional[dict] = None) -> Any:
        url = f"{self._base}{path}"
        data = json.dumps(body).encode() if body is not None else None
        request = urllib.request.Request(url, data=data, method=method)
        request.add_header("Authorization", self._api_key)
        request.add_header("Accept", "application/json")
        if data is not None:
            request.add_header("Content-Type", "application/json")
        try:
            with urllib.request.urlopen(request, timeout=TIMEOUT) as response:  # noqa: S310 - operator-supplied base
                raw = response.read().decode("utf-8")
                return json.loads(raw) if raw else {}
        except urllib.error.HTTPError as exc:
            detail = exc.read().decode("utf-8", "replace")[:600]
            raise ConfigError(f"{method} {path} -> HTTP {exc.code}: {detail}") from exc
        except (urllib.error.URLError, TimeoutError) as exc:
            raise ConfigError(f"{method} {path} -> {type(exc).__name__}: {exc}") from exc

    def get(self, path: str) -> Any:
        return self._request("GET", path)

    def write(self, method: str, path: str, body: dict) -> Any:
        if self._dry_run:
            print(f"    DRY-RUN would {method} {path}")
            return {}
        return self._request(method, path, body)


def _strip_underscored(value: Any) -> Any:
    """Drop `_comment`/`_controls_...` keys the template carries for humans.

    They are valid JSON but not FusionAuth fields, and PATCH would reject the
    nested ones.
    """
    if isinstance(value, dict):
        return {k: _strip_underscored(v) for k, v in value.items() if not k.startswith("_")}
    if isinstance(value, list):
        return [_strip_underscored(v) for v in value]
    return value


def load_template() -> dict:
    if not TEMPLATE.is_file():
        raise ConfigError(f"missing template: {TEMPLATE}")
    document = json.loads(TEMPLATE.read_text(encoding="utf-8"))
    tenant = document.get("tenant")
    if not isinstance(tenant, dict):
        raise ConfigError("template has no `tenant` object")
    return _strip_underscored(tenant)


def find_by_name(items: list[dict], name: str) -> Optional[dict]:
    return next((item for item in items if item.get("name") == name), None)


def ensure_tenant(client: Client, issuer: str) -> dict:
    tenants = client.get("/api/tenant").get("tenants", [])
    default = find_by_name(tenants, "Default")
    existing = find_by_name(tenants, TENANT_NAME)

    if existing and default and existing["id"] == default["id"]:
        raise ConfigError(
            "the tenant named 'JUVAl' IS the Default tenant -- Default must stay "
            "reserved for FusionAuth administration (ADR-031). Resolve by hand."
        )

    if existing:
        print(f"  tenant '{TENANT_NAME}' exists: {existing['id']}")
        tenant_id = existing["id"]
    else:
        print(f"  creating tenant '{TENANT_NAME}'")
        created = client.write("POST", "/api/tenant", {"tenant": {"name": TENANT_NAME}})
        tenant_id = created.get("tenant", {}).get("id", "<dry-run>")
        print(f"  tenant '{TENANT_NAME}' created: {tenant_id}")

    policy = load_template()
    policy["issuer"] = issuer
    policy.setdefault("minimumPasswordAge", {})
    policy["minimumPasswordAge"] = {"enabled": True, "seconds": MINIMUM_PASSWORD_AGE_SECONDS}
    policy["maximumPasswordAge"] = {"enabled": True, "days": MAXIMUM_PASSWORD_AGE_DAYS}

    print("  applying password / lockout / MFA policy to the tenant")
    client.write("PATCH", f"/api/tenant/{tenant_id}", {"tenant": policy})

    return {"id": tenant_id}


def ensure_application(client: Client, tenant_id: str) -> dict:
    applications = client.get("/api/application").get("applications", [])
    existing = find_by_name(applications, APPLICATION_NAME)

    # Least privilege (CLAUDE.md §4). The PWA has no browser login flow today
    # (no /oauth2/* is exposed -- ADR-031 §"Frontera de red"), so no production
    # redirect URI is invented here; the operator adds one when that flow is
    # built. authorization_code + refresh_token is the only sane future path;
    # implicit and client_credentials are deliberately absent.
    oauth = {
        "enabledGrants": list(LEAST_PRIVILEGE_GRANTS),
        "generateRefreshTokens": True,
        "requireClientAuthentication": False,
        "proofKeyForCodeExchangePolicy": "Required",
    }

    if existing:
        print(f"  application '{APPLICATION_NAME}' exists: {existing['id']}")
        if existing.get("tenantId") not in (None, tenant_id):
            raise ConfigError(
                f"application '{APPLICATION_NAME}' is under tenant "
                f"{existing.get('tenantId')}, not {tenant_id}. FusionAuth does not "
                "move an application between tenants -- delete it in the admin UI "
                "and re-run so it is recreated under the JUVAl tenant. Record the "
                "old and new application ids when you do (they are the OAuth "
                "client id / aud)."
            )
        app_id = existing["id"]
        client.write("PATCH", f"/api/application/{app_id}", {"application": {"oauthConfiguration": oauth}})
        return {"id": app_id}

    print(f"  creating application '{APPLICATION_NAME}' under tenant {tenant_id}")
    created = client.write(
        "POST",
        "/api/application",
        {"application": {"name": APPLICATION_NAME, "tenantId": tenant_id, "oauthConfiguration": oauth}},
    )
    app_id = created.get("application", {}).get("id", "<dry-run>")
    print(f"  application '{APPLICATION_NAME}' created: {app_id}")
    return {"id": app_id}


def ensure_roles(client: Client, app_id: str) -> None:
    if app_id == "<dry-run>":
        for role in REQUIRED_ROLES:
            print(f"    DRY-RUN would ensure role '{role}'")
        return
    application = client.get(f"/api/application/{app_id}").get("application", {})
    have = {role.get("name") for role in application.get("roles", [])}
    for role in REQUIRED_ROLES:
        if role in have:
            print(f"  role '{role}' exists")
            continue
        print(f"  creating role '{role}'")
        client.write(
            "POST",
            f"/api/application/{app_id}/role",
            {"role": {"name": role, "isDefault": False, "isSuperRole": False}},
        )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--base", default=os.environ.get("JUVAL_IDP_BASE", "http://127.0.0.1:9011"),
                        help="FusionAuth base URL (default: the SSH-forwarded local instance)")
    parser.add_argument("--issuer", default=os.environ.get("JUVAL_OIDC_ISSUER"),
                        help="tenant issuer. MUST become the public HTTPS URL before JUVAL_AUTH_MODE=oidc. "
                             "Defaults to --base, which is only valid for configuration evidence.")
    parser.add_argument("--dry-run", action="store_true", help="print the writes without making them")
    args = parser.parse_args()

    api_key = os.environ.get("JUVAL_IDP_API_KEY")
    if not api_key:
        print("JUVAL_IDP_API_KEY is not set. Create a FusionAuth API key in the admin UI\n"
              "(Settings -> API Keys), grant it Tenants + Applications write, and pass it in\n"
              "the environment -- never as an argument.", file=sys.stderr)
        return 2

    issuer = (args.issuer or args.base).rstrip("/")
    local = issuer.startswith("http://") or "127.0.0.1" in issuer or "localhost" in issuer

    print(f"FusionAuth: {args.base}")
    print(f"tenant issuer: {issuer}")
    if local:
        print("  NOTE: this is a LOCAL issuer. Tokens carry it for configuration evidence\n"
              "  only. Re-run with --issuer <public https url> before activating the backend.")
    if args.dry_run:
        print("  DRY RUN -- no writes will be made")
    print()

    client = Client(args.base, api_key, args.dry_run)

    try:
        if client.get("/api/status").get("status") != "Ok":
            raise ConfigError("instance did not report status Ok")
        client.get("/api/tenant")  # 401 here means the API key is bad
        print("preflight: instance up, API key accepted\n")

        tenant = ensure_tenant(client, issuer)
        application = ensure_application(client, tenant["id"])
        ensure_roles(client, application["id"])
    except ConfigError as exc:
        print(f"\nFAILED: {exc}", file=sys.stderr)
        return 1

    print()
    print("done. Backend configuration (no secret in here -- the backend verifies")
    print("tokens with the issuer's PUBLIC JWKS):")
    print()
    print(f"  JUVAL_AUTH_MODE=oidc            # only after tools/verify_oidc.py passes against a PUBLIC issuer")
    print(f"  JUVAL_OIDC_ISSUER={issuer}")
    print(f"  JUVAL_OIDC_AUDIENCE={application['id']}")
    print(f"  JUVAL_OIDC_ROLES_CLAIM=roles")
    print()
    print("Next: tools/verify_oidc.py --issuer <issuer> --tenant-policy ; then tools/verify_rbac.py")
    return 0


if __name__ == "__main__":
    sys.exit(main())
